main: 
	gcc ./adt/arraydin/arraydin.c ./adt/mesinkarakter/mesinkarakter.c ./adt/mesinkata/mesinkata.c ./procedure/load/load.c ./adt/kata/kata.c main.c -o ./bin/main

dinerdash:
	gcc ./games/dinerdash/dinerdash.c  ./adt/masakan/masakan.c ./adt/order/order.c ./adt/kata/kata.c boolean.h -o ./bin/dinerdash

randomnumber:
	gcc ./games/rng/randomnumber.c ./games/rng/rng.c -o ./bin/randomnumber

rng:
	gcc ./games/rng/rng.c -o ./bin/rng